/**
 * pac-server.js — Local PAC file HTTP server
 *
 * Runs locally on 127.0.0.1:8182 and serves /proxy.pac.
 * Accepts configuration via:
 * 1. HTTP POST /update (JSON body)
 * 2. stdin JSON messages: { type: 'update', config: { ... } }
 *
 * Config format:
 *   {
 *     "proxyHost": "1.2.3.4",
 *     "proxyPort": 3128,
 *     "enabledHosts": ["*.instagram.com", "*.x.com"],
 *     "customDomains": ["mysite.com"]
 *   }
 */

'use strict';

const http = require('http');

const PAC_PORT = parseInt(process.env.PAC_PORT ?? '8182', 10);

// ── Current config ────────────────────────────────────────────────────────────
let config = {
  proxyHost:     process.env.PROXY_HOST     ?? '127.0.0.1',
  proxyPort:     parseInt(process.env.PROXY_PORT ?? '3128', 10),
  enabledHosts:  [],
  customDomains: [],
};

// ── PAC generator ─────────────────────────────────────────────────────────────
function generatePac(cfg) {
  const proxy = `PROXY ${cfg.proxyHost}:${cfg.proxyPort}`;
  
  // Normalize hosts: custom domains become wildcard patterns
  const normalizedCustom = (cfg.customDomains || []).map(d => {
    const trimmed = d.trim().replace(/^\*\./, '');
    return `*.${trimmed}`;
  });
  
  const allHosts = [...(cfg.enabledHosts || []), ...normalizedCustom];

  const conditions = allHosts
    .map(h => `    shExpMatch(host, "${h}")`)
    .join(' ||\n');

  return `// Proxy Auto-Configuration (PAC) — generated by Proxy Router Desktop
// Updated at: ${new Date().toISOString()}

function FindProxyForURL(url, host) {
  var proxy = "${proxy}";

  // Direct connection for localhost / intranet
  if (isPlainHostName(host) || host === "localhost" || host === "127.0.0.1") {
    return "DIRECT";
  }

${conditions ? `  if (\n${conditions}\n  ) {\n    return proxy;\n  }` : '  // No routed domains configured'}

  return "DIRECT";
}
`;
}

let currentPac = generatePac(config);

function setCors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

// ── HTTP Server ───────────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  setCors(res);

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  const url = req.url.split('?')[0];

  if (req.method === 'GET' && (url === '/proxy.pac' || url === '/')) {
    res.writeHead(200, {
      'Content-Type': 'application/x-ns-proxy-autoconfig',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
    });
    res.end(currentPac);
    return;
  }

  if (req.method === 'GET' && url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, port: PAC_PORT }));
    return;
  }

  if (req.method === 'GET' && url === '/status') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, config }));
    return;
  }

  if (req.method === 'POST' && url === '/update') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try {
        const payload = JSON.parse(body || '{}');
        config = { ...config, ...payload };
        currentPac = generatePac(config);
        console.log(`[pac-server] Updated rules. Total hosts: ${(config.enabledHosts?.length || 0) + (config.customDomains?.length || 0)}`);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true, message: 'PAC regenerated' }));
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: false, error: 'Invalid JSON' }));
      }
    });
    return;
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not found' }));
});

server.listen(PAC_PORT, '127.0.0.1', () => {
  process.send?.({ type: 'ready', url: `http://127.0.0.1:${PAC_PORT}/proxy.pac` });
  console.log(`[pac-server] Running on http://127.0.0.1:${PAC_PORT}/proxy.pac`);
});

// ── IPC via stdin: backup channel for parent processes ────────────────────────
let stdinBuf = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => {
  stdinBuf += chunk;
  const lines = stdinBuf.split('\n');
  stdinBuf = lines.pop();
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      const msg = JSON.parse(trimmed);
      if (msg.type === 'update') {
        config = { ...config, ...msg.config };
        currentPac = generatePac(config);
        process.send?.({ type: 'updated' });
      }
    } catch {
      // ignore parsing errors
    }
  }
});

process.on('SIGTERM', () => server.close(() => process.exit(0)));
process.on('SIGINT', () => server.close(() => process.exit(0)));
